#ifndef CONSTANT_H
#define CONSTANT_H

#define DATA_PIN D0
#define SINGLE_MATRIX_ROWS 16
#define SINGLE_MATRIX_COLS 16
#define SINGLE_MATRIX_LEDS (SINGLE_MATRIX_ROWS * SINGLE_MATRIX_COLS)
#define NUMBER_OF_MATRIX 3
#define TOTAL_MATRIX_LEDS (SINGLE_MATRIX_ROWS * SINGLE_MATRIX_COLS * NUMBER_OF_MATRIX)

#define TOTAL_MATRIX_ROWS (SINGLE_MATRIX_ROWS * NUMBER_OF_MATRIX)
#define TOTAL_MATRIX_COLS (SINGLE_MATRIX_COLS * NUMBER_OF_MATRIX)

#define ASCII_ROWS 6

#endif